/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";
import { useTrimeshCollision } from "spacesvr";
import { BufferGeometry } from "three";

type GLTFResult = GLTF & {
  nodes: {
    building6_1: THREE.Mesh;
    building6_2: THREE.Mesh;
    building6_3: THREE.Mesh;
    windows6: THREE.Mesh;
    building5_1: THREE.Mesh;
    building5_2: THREE.Mesh;
    windows5: THREE.Mesh;
    building4_1: THREE.Mesh;
    building4_2: THREE.Mesh;
    windows4: THREE.Mesh;
    building1: THREE.Mesh;
    building1_1: THREE.Mesh;
    windows1: THREE.Mesh;
    lights: THREE.Mesh;
    fence3: THREE.Mesh;
    fence1: THREE.Mesh;
    fence2: THREE.Mesh;
    tables: THREE.Mesh;
    house3: THREE.Mesh;
    building3_1: THREE.Mesh;
    building3_2: THREE.Mesh;
    house2: THREE.Mesh;
    building2_1: THREE.Mesh;
    building2_2: THREE.Mesh;
    road: THREE.Mesh;
    well_1: THREE.Mesh;
    well_2: THREE.Mesh;
    logs: THREE.Mesh;
    tree: THREE.Mesh;
    sign_1: THREE.Mesh;
    sign_2: THREE.Mesh;
    sign_3: THREE.Mesh;
    curb: THREE.Mesh;
    lampost: THREE.Mesh;
    bench: THREE.Mesh;
    fence4: THREE.Mesh;
    chest_base: THREE.Mesh;
    chest_base_1: THREE.Mesh;
    chest_base_2: THREE.Mesh;
    chest_base_3: THREE.Mesh;
    chest_base_4: THREE.Mesh;
    chest_lid_1: THREE.Mesh;
    chest_lid_2: THREE.Mesh;
    chest_lid_3: THREE.Mesh;
    monument_1: THREE.Mesh;
    monument_2: THREE.Mesh;
    samurai: THREE.Mesh;
    keg_1: THREE.Mesh;
    keg_2: THREE.Mesh;
    flowerpot_1: THREE.Mesh;
    flowerpot_2: THREE.Mesh;
    flowerpot_3: THREE.Mesh;
    bridge: THREE.Mesh;
    lanterns: THREE.Mesh;
    temple: THREE.Mesh;
  };
  materials: {
    ["surfaces.mat"]: THREE.MeshStandardMaterial;
    ["black.mat"]: THREE.MeshStandardMaterial;
    ["surfaces2.mat"]: THREE.MeshStandardMaterial;
    ["black1.mat"]: THREE.MeshStandardMaterial;
    ["mat.black.2"]: THREE.MeshStandardMaterial;
    ["gold.mat"]: THREE.MeshStandardMaterial;
    ["blue_metal.mat"]: THREE.MeshStandardMaterial;
    ["Multi.001"]: THREE.MeshStandardMaterial;
    ["wood.mat"]: THREE.MeshStandardMaterial;
    ["Wood.001"]: THREE.MeshStandardMaterial;
    ["white.mat"]: THREE.MeshStandardMaterial;
  };
};

const FILE_URL =
  "https://d27rt3a60hh1lx.cloudfront.net/models/Town-1620552474/japanese_town_2.glb.gz";

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF(FILE_URL) as GLTFResult;

  const SCALE = 19;

  useTrimeshCollision(
    (nodes.road.geometry.clone() as BufferGeometry)
      .translate(0, 0.257, 0)
      .scale(SCALE, SCALE, SCALE)
  );

  useTrimeshCollision(
    (nodes.curb.geometry.clone() as BufferGeometry)
      .translate(0, 0.257, 0)
      .scale(SCALE, SCALE, SCALE)
  );

  useEffect(() => {
    if (group.current) {
      group.current.traverse((child) => {
        child.castShadow = true;
        child.receiveShadow = true;
      });
    }
  }, []);

  return (
    <group name="japanese_town" ref={group} {...props} dispose={null}>
      <group name="Scene" scale={SCALE}>
        <group position-y={0.257}>
          <group name="house6">
            <group name="building6">
              <mesh
                name="building6_1"
                geometry={nodes.building6_1.geometry}
                material={nodes.building6_1.material}
              />
              <mesh
                name="building6_2"
                geometry={nodes.building6_2.geometry}
                material={nodes.building6_2.material}
              />
              <mesh
                name="building6_3"
                geometry={nodes.building6_3.geometry}
                material={materials["black.mat"]}
              />
            </group>
            <mesh
              name="windows6"
              geometry={nodes.windows6.geometry}
              material={nodes.windows6.material}
            />
          </group>
          <group name="house5">
            <group name="building5">
              <mesh
                name="building5_1"
                geometry={nodes.building5_1.geometry}
                material={nodes.building5_1.material}
              />
              <mesh
                name="building5_2"
                geometry={nodes.building5_2.geometry}
                material={nodes.building5_2.material}
              />
            </group>
            <mesh
              name="windows5"
              geometry={nodes.windows5.geometry}
              material={nodes.windows5.material}
            />
          </group>
          <group name="house4">
            <group name="building4">
              <mesh
                name="building4_1"
                geometry={nodes.building4_1.geometry}
                material={nodes.building4_1.material}
              />
              <mesh
                name="building4_2"
                geometry={nodes.building4_2.geometry}
                material={nodes.building4_2.material}
              />
            </group>
            <mesh
              name="windows4"
              geometry={nodes.windows4.geometry}
              material={nodes.windows4.material}
            />
          </group>
          <group name="house1">
            <group name="buliding1">
              <mesh
                name="building1"
                geometry={nodes.building1.geometry}
                material={nodes.building1.material}
              />
              <mesh
                name="building1_1"
                geometry={nodes.building1_1.geometry}
                material={nodes.building1_1.material}
              />
            </group>
            <mesh
              name="windows1"
              geometry={nodes.windows1.geometry}
              material={nodes.windows1.material}
            />
          </group>
          <mesh
            name="lights"
            geometry={nodes.lights.geometry}
            material={nodes.lights.material}
          />
          <mesh
            name="fence3"
            geometry={nodes.fence3.geometry}
            material={nodes.fence3.material}
          />
          <mesh
            name="fence1"
            geometry={nodes.fence1.geometry}
            material={nodes.fence1.material}
          />
          <mesh
            name="fence2"
            geometry={nodes.fence2.geometry}
            material={nodes.fence2.material}
          />
          <mesh
            name="tables"
            geometry={nodes.tables.geometry}
            material={nodes.tables.material}
          />
          <mesh
            name="house3"
            geometry={nodes.house3.geometry}
            material={nodes.house3.material}
          >
            <group name="building3">
              <mesh
                name="building3_1"
                geometry={nodes.building3_1.geometry}
                material={nodes.building3_1.material}
              />
              <mesh
                name="building3_2"
                geometry={nodes.building3_2.geometry}
                material={nodes.building3_2.material}
              />
            </group>
          </mesh>
          <mesh
            name="house2"
            geometry={nodes.house2.geometry}
            material={nodes.house2.material}
          >
            <group name="building2">
              <mesh
                name="building2_1"
                geometry={nodes.building2_1.geometry}
                material={nodes.building2_1.material}
              />
              <mesh
                name="building2_2"
                geometry={nodes.building2_2.geometry}
                material={nodes.building2_2.material}
              />
            </group>
          </mesh>
          <mesh
            name="road"
            geometry={nodes.road.geometry}
            material={nodes.road.material}
          />
          <group name="well">
            <mesh
              name="well_1"
              geometry={nodes.well_1.geometry}
              material={nodes.well_1.material}
            />
            <mesh
              name="well_2"
              geometry={nodes.well_2.geometry}
              material={nodes.well_2.material}
            />
          </group>
          <mesh
            name="logs"
            geometry={nodes.logs.geometry}
            material={nodes.logs.material}
          />
          <mesh
            name="tree"
            geometry={nodes.tree.geometry}
            material={nodes.tree.material}
          />
          <group name="sign">
            <mesh
              name="sign_1"
              geometry={nodes.sign_1.geometry}
              material={nodes.sign_1.material}
            />
            <mesh
              name="sign_2"
              geometry={nodes.sign_2.geometry}
              material={nodes.sign_2.material}
            />
            <mesh
              name="sign_3"
              geometry={nodes.sign_3.geometry}
              material={materials["mat.black.2"]}
            />
          </group>
          <mesh
            name="curb"
            geometry={nodes.curb.geometry}
            material={nodes.curb.material}
          />
          <mesh
            name="lampost"
            geometry={nodes.lampost.geometry}
            material={nodes.lampost.material}
          />
          <mesh
            name="bench"
            geometry={nodes.bench.geometry}
            material={nodes.bench.material}
          />
          <mesh
            name="fence4"
            geometry={nodes.fence4.geometry}
            material={nodes.fence4.material}
          />
          <group name="chest">
            <mesh
              name="chest_base"
              geometry={nodes.chest_base.geometry}
              material={materials["gold.mat"]}
            />
            <mesh
              name="chest_base_1"
              geometry={nodes.chest_base_1.geometry}
              material={nodes.chest_base_1.material}
            />
            <mesh
              name="chest_base_2"
              geometry={nodes.chest_base_2.geometry}
              material={nodes.chest_base_2.material}
            />
            <mesh
              name="chest_base_3"
              geometry={nodes.chest_base_3.geometry}
              material={materials["wood.mat"]}
            />
            <mesh
              name="chest_base_4"
              geometry={nodes.chest_base_4.geometry}
              material={nodes.chest_base_4.material}
            />
            <group name="chest_lid">
              <mesh
                name="chest_lid_1"
                geometry={nodes.chest_lid_1.geometry}
                material={nodes.chest_lid_1.material}
              />
              <mesh
                name="chest_lid_2"
                geometry={nodes.chest_lid_2.geometry}
                material={nodes.chest_lid_2.material}
              />
              <mesh
                name="chest_lid_3"
                geometry={nodes.chest_lid_3.geometry}
                material={nodes.chest_lid_3.material}
              />
            </group>
          </group>
          <group name="monument">
            <mesh
              name="monument_1"
              geometry={nodes.monument_1.geometry}
              material={nodes.monument_1.material}
            />
            <mesh
              name="monument_2"
              geometry={nodes.monument_2.geometry}
              material={nodes.monument_2.material}
            />
          </group>
          <mesh
            name="samurai"
            geometry={nodes.samurai.geometry}
            material={nodes.samurai.material}
            rotation={[-0.0072, 0.007, 0.009]}
          />
          <group name="keg">
            <mesh
              name="keg_1"
              geometry={nodes.keg_1.geometry}
              material={nodes.keg_1.material}
            />
            <mesh
              name="keg_2"
              geometry={nodes.keg_2.geometry}
              material={nodes.keg_2.material}
            />
          </group>
          <group name="flowerpot">
            <mesh
              name="flowerpot_1"
              geometry={nodes.flowerpot_1.geometry}
              material={nodes.flowerpot_1.material}
            />
            <mesh
              name="flowerpot_2"
              geometry={nodes.flowerpot_2.geometry}
              material={nodes.flowerpot_2.material}
            />
            <mesh
              name="flowerpot_3"
              geometry={nodes.flowerpot_3.geometry}
              material={materials["white.mat"]}
            />
          </group>
          <mesh
            name="bridge"
            geometry={nodes.bridge.geometry}
            material={nodes.bridge.material}
          />
          <mesh
            name="lanterns"
            geometry={nodes.lanterns.geometry}
            material={nodes.lanterns.material}
          />
          <mesh
            name="temple"
            geometry={nodes.temple.geometry}
            material={nodes.temple.material}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(FILE_URL);
